name: C/C++ CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential && sudo apt-get install -y cmake && sudo apt-get install -y uuid-dev && sudo apt-get install -y zlib1g-dev
    - name: install famfs_ioctl.h
      run: sudo cp ${GITHUB_WORKSPACE}/linux/famfs_ioctl.h /usr/include/linux/
    - name: make
      run: make all
    - name: make test
      run: make test
