name: C/C++ CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential
      run: sudo apt install -y cmake
      run: sudo apt install -y uuid-dev
      run: sudo apt install -y zlib1g-dev
    - name: make
      run: make all
    - name: make test
      run: make test
